// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileName() {
  return window['go']['main']['App']['GetFileName']();
}

export function OnVditorChanged(arg1) {
  return window['go']['main']['App']['OnVditorChanged'](arg1);
}

export function ResizeWindows() {
  return window['go']['main']['App']['ResizeWindows']();
}
