// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileName() {
  return window['go']['main']['App']['GetFileName']();
}

export function LoadContentFromLocal() {
  return window['go']['main']['App']['LoadContentFromLocal']();
}

export function OS() {
  return window['go']['main']['App']['OS']();
}

export function OnVditorValueChanged(arg1) {
  return window['go']['main']['App']['OnVditorValueChanged'](arg1);
}

export function ResizeWindow() {
  return window['go']['main']['App']['ResizeWindow']();
}
